---
- name: Wordpress configuration

  hosts: mysql

  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted
      become: yes

  tasks:
    - name: 'Install MySQL and dependencies'
      apt:
        name: 
        - mysql-server-5.7
        - python3-mysqldb
        - php7.2-mysql
        state: latest
      become: yes

    - name: 'Create MySQL database'
      mysql_db: 
        name: wordpress_db
        login_user: root
        state: present
      become: yes

    - name: 'Create MySQL user'
      mysql_user:
        login_user: root
        name: wordpress
        password: 12345
        priv: 'wordpress_db.*:ALL'
        host: '{{ item }}'
        state: present
      with_items:
        - localhost
        - '127.0.0.1'
        - '192.168.182.12'
      become: yes

    - name: 'Set-up MySQL to allow remote connection'
      copy:
        src: '/configs/mysqld.cnf'
        dest: '/etc/mysql/mysql.conf.d/mysqld.cnf'
        remote_src: yes
      become: yes
      notify:
        - restart mysql

- hosts: wordpress

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
      become: yes

  tasks:
    - name: 'Install PHP and dependencies'
      apt:
        name: 
        - php7.2
        - apache2
        - libapache2-mod-php7.2
        - php7.2-gd
        - php-ssh2
        - php7.2-mysql
        state: latest
      become: yes

    - name: 'Download and extract latest version of Wordpress'
      unarchive:
        src: 'https://wordpress.org/latest.tar.gz'
        dest: '/var/www'
        remote_src: yes
      become: yes

    - name: 'Copy Wordpress configuration file'
      copy:
        src: '/var/www/wordpress/wp-config-sample.php'
        dest: '/var/www/wordpress/wp-config.php'
        remote_src: yes
      become: yes

    - name: 'Set-up database configuration'     
      replace:
        path: '/var/www/wordpress/wp-config.php'
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
      with_items:
        - { regex: 'database_name_here', value: 'wordpress_db'}
        - { regex: 'username_here', value: 'wordpress'}
        - { regex: 'password_here', value: '12345'}
        - { regex: 'localhost', value: '192.168.182.13'}
      become: yes

    - name: 'Set-up Apache to run Wordpress'
      copy:
        src: '/configs/000-default.conf'
        dest: '/etc/apache2/sites-available/000-default.conf'
        remote_src: yes
      become: yes
      notify: 
        - restart apache